[dev]
  functions = "functions"
  functionsPort = 7000
[build]
  publish = "dist/bouffe/browser"
  command = "ng build"
  functions = "./functions"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
